name: CI/CD para mi Web en Docker

on:
  push:
    branches:
      - main  # Ejecutar el pipeline en cada push a la rama "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir la imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mi-web-docker:latest .

      - name: Subir la imagen a Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mi-web-docker:latest

  deploy:
    runs-on: self-hosted  # Servidor que ejecuta el contenedor
    needs: build-and-push
    steps:
      - name: Descargar nueva imagen
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/mi-web-docker:latest

      - name: Detener el contenedor anterior
        run: docker stop mi-web-container || true && docker rm mi-web-container || true

      - name: Ejecutar el nuevo contenedor
        run: docker run -d -p 8080:80 --name mi-web-container ${{ secrets.DOCKER_USERNAME }}/mi-web-docker:latest
